service: customcdn

provider:
  name: aws
  runtime: dotnetcore2.1
  region: eu-central-1

package:
  artifact: src/Input/bin/release/netcoreapp2.1/deploy-package.zip

functions:
  input:
    handler: Input::Input.InputFunction::FunctionHandler
    events:
    - http:
        path: input
        method: post

resources:
  Resources:
    ImageQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "ImageQueue"